[package]
name = "alignnet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "alignnet"
path = "src/main.rs"

[dependencies]
# engine = { path = "../../engine", version = "*", features = ["tuner"] }
rand = "0.9.2"

[lints]
workspace = true
