const _NUMBER_OF_SIDES: u32 = 2;
const _NUMBER_OF_PIECES: u32 = 6;
const _NUMBER_OF_RANKS: u32 = 8;
const _NUMBER_OF_FILES: u32 = 8;
const _NUMBER_OF_SQUARES: u32 = _NUMBER_OF_FILES * _NUMBER_OF_FILES;
